### ISSUE TITLE
Define IObject - a base interface for objects in SmartActors

### ISSUE THREAD

**Issue by etyumentcev** [SmartTools/smartactors#1]
Like code in C#
interface IObject
{
   object getValue(string name);
   void setValue(string name, object obj);
};

if you try to get a field from an IObject but there is no suitable property getValue should return a null value.

setValue should rewrite an exisiting value.

Should develop a number of test helpers to meet behaviour of this interface.
Should develop unit tests for test helpers. :)

**Comment by omskscream** [comment]
Interface implemented, tests created.

**Comment by etyumentcev** [comment]
For now I will decide should we close task or not.

**Comment by omskscream** [comment]
Ok

**Comment by omskscream** [comment]
I think we should close this issue after merge.
